// /d/shenlong/wanted_list.h
// Last Modified by winder on Jul. 12 2002

mapping wanted_list = ([
	"°×Áú½£"   : "/clone/weapon/treasure/baihong-jian.c",
	"Ø°Ê×"     : "/clone/weapon/treasure/bishou.c",
	"ÍÀÁúµ¶"   : "/clone/weapon/treasure/dragonblade.c",
	"·üÄ§µ¶"   : "/clone/weapon/treasure/fumo-dao.c",
	"¸É½«½£"   : "/clone/weapon/treasure/ganjiang-jian.c",
	"±ÌË®½£"   : "/clone/weapon/treasure/greenwater-sword.c",
	"Îå¶¾¼ô"   : "/clone/weapon/treasure/jiandao.c",
	"½ğ·ï¹³"   : "/clone/weapon/treasure/jinfenggou.c",
	"¶áÃü½ğ»¨" : "/clone/weapon/treasure/jinhua.c",
	"½ğÂÖ"     : "/clone/weapon/treasure/jinlun.c",
	"½ğÉß½£"   : "/clone/weapon/treasure/jinshe-jian.c",
	"½ğÎÚÕÈ"   : "/clone/weapon/treasure/jinwu-staff.c",
	"´³Íõ±¦µ¶" : "/clone/weapon/treasure/king-blade.c",
	"ÀÇÑÀ°ô"   : "/clone/weapon/treasure/langyabang.c",
	"ÁéÉßÕÈ"   : "/clone/weapon/treasure/lingshezhang.c",
	"Á¤ÈªÇ¹"   : "/clone/weapon/treasure/liquan-qiang.c",
	"ÁúÈª½£"   : "/clone/weapon/treasure/longquan-jian.c",
	"ÄªĞ°½£"   : "/clone/weapon/treasure/moye-jian.c",
	"°×ÓñÑşÇÙ" : "/clone/weapon/treasure/qin.c",
	"Çà¹â½£"   : "/clone/weapon/treasure/qingguang-jian.c",
	"ÄÏº£ÉñÄ¾" : "/clone/weapon/treasure/sea-wood.c",
	"ÒĞÌì½£"   : "/clone/weapon/treasure/skysword.c",
	"Ñªµ¶"     : "/clone/weapon/treasure/xblade.c",
	"ĞşÌú½£"   : "/clone/weapon/treasure/xuantie-sword.c",
	"ĞşÌúÖØ½£" : "/clone/weapon/treasure/xuantie-jian.c",
	"ÒøÂÖ"     : "/clone/weapon/treasure/yinlun.c",
	"ÓÎÁú½£"   : "/clone/weapon/treasure/youlong-jian.c",
	"Óã³¦½£"   : "/clone/weapon/treasure/yuchang-jian.c",
	"Ô½Íõ½£"   : "/clone/weapon/treasure/yuewang-jian.c",
	"Õ¿Â¬½£"   : "/clone/weapon/treasure/zhanlu-jian.c",
	"ÕæÎä½£"   : "/clone/weapon/treasure/zhenwu-jian.c",
	"½ğÉß×¶"   : "/d/jinshe/obj/jinshe-zhui.c",
	"ÂÌÓñ°ô"   : "/kungfu/class/gaibang/obj/lvyv_bang.c",
]);
