//killer's skill by cool 98.6.11

string *k_force =({ 
	"qiantian-yiyang",
	"huntian-qigong",
	"yijin-jing",
	"bihai-chaosheng",
	"linji-zhuang",
	"yunu-xinjing",
	"xiantian-gong",
	"zixia-gong",
	"xuantian-wuji",
	"guiyuan-tunafa",
	"yinyun-ziqi",
	"shenghuo-shengong",
	"huagong-dafa",
	"shenyuan-gong",});
string *k_dodge =({ 
	"piaoyi-shenfa",
	"suibo-zhuliu",
	"tianlong-xiang",
	"tiyunzong",
	"shaolin-shenfa",
	"yunu-shenfa",
	"kunlun-shenfa",
	"shuishangpiao",
	"yanling-shenfa",
	"zhaixingshu", 
	"xiaoyaoyou",
	"anying-fuxiang",});

mapping *skill1=({
/*cuff*/
	(["t_skill" :		"wudang-quan",
		"b_skill" :		"cuff",]),
	(["t_skill" :		"taizu-quan",
		"b_skill" :		"cuff",]),	
	(["t_skill" :		"luohan-quan",
		"b_skill" :		"cuff",]),	
	(["t_skill" :		"meinu-quanfa",
		"b_skill" :		"cuff",]), 
	(["t_skill" :		"wenjia-quan",
		"b_skill" :		"cuff",]), 
/*strike*/
	(["t_skill" :		"qingyan-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"hanbing-mianzhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"xingyi-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"sanhua-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"weituo-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"luoying-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"kunlun-zhang",
		"b_skill" :		"strike",]), 
	(["t_skill" :		"tiangang-zhang",
		"b_skill" :		"strike",]),
/*hand*/
	(["t_skill" :		"fengyun-shou",
		"b_skill" :		"hand",]),
	(["t_skill" :		"yingzhua-shou",
		"b_skill" :		"hand",]),
	(["t_skill" :		"suohou-shou",
		"b_skill" :		"hand",]),
/*leg*/
	(["t_skill" :		"shaolin-tantui",
		"b_skill" :		"leg",]),
	(["t_skill" :		"xuanfeng-tui",
		"b_skill" :		"leg",]),
/*finger*/	
	(["t_skill" :		"canhe-zhi",
		"b_skill" :		"finger",]),
	(["t_skill" :		"mohe-zhi",
		"b_skill" :		"finger",]),
//	(["t_skill" :		"nianhua-zhi",
//	"b_skill" :		"finger",]),
/*claw*/	
	(["t_skill" :		"yingzhua-gong",
		"b_skill" :		"claw",]),
	(["t_skill" :		"jimie-zhua",
		"b_skill" :		"claw",]),
});
mapping *blade1=({
/*blade*/
	(["t_skill" :		"xuanxu-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]), 
	(["t_skill" :		"yanxing-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]), 
	(["t_skill" :		"wenjia-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"lieyan-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"xiuluo-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"murong-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"liuhe-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
});
mapping *sword1=({

/*sword*/
	(["t_skill" :		"murong-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]), 
	(["t_skill" :		"damo-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"fumo-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"liangyi-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]), 
	(["t_skill" :		"huifeng-jian",
		"b_skill" :		"sword",
	"weapon" :		"sword",]),	
 	(["t_skill" :		"yunu-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"yuxiao-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"liehuo-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
});
mapping *club1=({

/*club*/	
	(["t_skill" :		"weituo-gun",
		"b_skill" :		"club",
		"weapon" :		"club",]),	
 	(["t_skill" :		"zui-gun",
		"b_skill" :		"club",
		"weapon" :		"club",]),	
});
mapping *staff1=({

/*staff*/	
	(["t_skill" :		"baituo-shezhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
	(["t_skill" :		"fengmo-zhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
	(["t_skill" :		"wuchang-zhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
	(["t_skill" :		"tianshan-zhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
});
mapping *whip1=({
/*whip*/
	(["t_skill" :		"yuxu-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	
	(["t_skill" :		"qingxu-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	
	(["t_skill" :		"huifeng-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	
});
mapping *skill2=({
/*cuff*/
	(["t_skill" :		"taiji-quan",
		"b_skill" :		"cuff",]),
	(["t_skill" :		"taizu-quan",
		"b_skill" :		"cuff",]),	
	(["t_skill" :		"jingang-quan",
		"b_skill" :		"cuff",]),	
	(["t_skill" :		"kongming-quan",
		"b_skill" :		"cuff",]), 
	(["t_skill" :		"poyu-quan",
		"b_skill" :		"cuff",]), 
	(["t_skill" :		"qishang-quan",
		"b_skill" :		"cuff",]), 
	(["t_skill" :		"meinu-quanfa",
		"b_skill" :		"cuff",]), 
	(["t_skill" :		"wenjia-quan",
		"b_skill" :		"cuff",]), 
/*strike*/
	(["t_skill" :		"qingyan-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"hanbing-mianzhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"xingyi-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"sanhua-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"banruo-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"chousui-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"hunyuan-zhang",
		"b_skill" :		"strike"]),
	(["t_skill" :		"jinding-mianzhang",
		"b_skill" :		"strike"]),
	(["t_skill" :		"jinshe-zhangfa",
		"b_skill" :		"strike"]),
	(["t_skill" :		"luoying-zhang",
		"b_skill" :		"strike",]),	
	(["t_skill" :		"kunlun-zhang",
		"b_skill" :		"strike",]), 
	(["t_skill" :		"tiangang-zhang",
		"b_skill" :		"strike",]),
	(["t_skill" :		"sixiang-zhang",
		"b_skill" :		"strike",]),
	(["t_skill" :		"tiezhang-zhangfa",
		"b_skill" :		"strike",]),
	(["t_skill" :		"xianglong-zhang",
		"b_skill" :		"strike",]),
/*hand*/
	(["t_skill" :		"yingzhua-shou",
		"b_skill" :		"hand",]),
	(["t_skill" :		"suohou-shou",
		"b_skill" :		"hand",]),
	(["t_skill" :		"jieshou-jiushi",
		"b_skill" :		"hand",]),
	(["t_skill" :		"juehu-shou",
		"b_skill" :		"hand",]),
//	(["t_skill" :		"lanhua-shou",
//		"b_skill" :		"hand",]),
	(["t_skill" :		"qianye-shou",
		"b_skill" :		"hand",]),
//	(["t_skill" :		"qianzhu-wandushou",
//	"b_skill" :		"hand",]),
//	(["t_skill" :		"zhemei-shou",
//	"b_skill" :		"hand",]),
/*leg*/
	(["t_skill" :		"ruying-suixingtui",
		"b_skill" :		"leg",]),
	(["t_skill" :		"xuanfeng-tui",
		"b_skill" :		"leg",]),
/*finger*/
	(["t_skill" :		"yiyang-zhi",
		"b_skill" :		"finger",]),
	(["t_skill" :		"yizhi-chan",
		"b_skill" :		"finger",]),
	(["t_skill" :		"tanzhi-shentong",
		"b_skill" :		"finger",]),
	(["t_skill" :		"canhe-zhi",
		"b_skill" :		"finger",]),
	(["t_skill" :		"nianhua-zhi",
		"b_skill" :		"finger",]),
/*claw*/
	(["t_skill" :		"yingzhua-gong",
		"b_skill" :		"claw",]),
	(["t_skill" :		"jimie-zhua",
		"b_skill" :		"claw",]),
	(["t_skill" :		"longzhua-gong",
		"b_skill" :		"claw",]),

});
mapping *blade2=({
/*blade*/
	(["t_skill" :		"ranmu-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]), 
	(["t_skill" :		"yanxing-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]), 
	(["t_skill" :		"wenjia-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"lieyan-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"xiuluo-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"murong-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"liuhe-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"cibei-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"fanliangyi-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"ruyi-dao",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
	(["t_skill" :		"shandian-daofa",
		"b_skill" :		"blade",
		"weapon" :		"blade",]),	
});
mapping *sword2=({

/*sword*/
	(["t_skill" :		"murong-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]), 
	(["t_skill" :		"damo-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"taiji-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"liangyi-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]), 
	(["t_skill" :		"huifeng-jian",
		"b_skill" :		"sword",
	"weapon" :		"sword",]),	
 	(["t_skill" :		"yunu-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"yuxiao-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"liehuo-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"jinshe-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"bixie-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"qingmang-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"xuantie-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"songshan-jian",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
	(["t_skill" :		"huashan-jianfa",
		"b_skill" :		"sword",
		"weapon" :		"sword",]),	
});
mapping *club2=({

/*club*/
	(["t_skill" :		"weituo-gun",
		"b_skill" :		"club",
		"weapon" :		"club",]),	
	(["t_skill" :		"weituo-chu",
		"b_skill" :		"club",
		"weapon" :		"club",]),	
 	(["t_skill" :		"zui-gun",
		"b_skill" :		"club",
		"weapon" :		"club",]),	
});
mapping *staff2=({

/*staff*/
	(["t_skill" :		"baituo-shezhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
	(["t_skill" :		"tianshan-zhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
	(["t_skill" :		"fengmo-zhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
	(["t_skill" :		"wuchang-zhang",
		"b_skill" :		"staff",
		"weapon" :		"staff",]),	
});
mapping *whip2=({

/*whip*/
	(["t_skill" :		"yuxu-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	
	(["t_skill" :		"qingxu-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	
	(["t_skill" :		"huifeng-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	
	(["t_skill" :		"riyue-bian",
		"b_skill" :		"whip",
		"weapon" :		"whip",]),	

});
