// /d/yixing/doc/info_bang.h
// Last Modified by winder on Jul. 12 2002

mapping info_bang = ([
	"铁叉帮" : "尤得胜",
	"飞鱼帮" : "成大洋",
//	"长乐帮" : "司徒横",
	"天河帮" : "黄伯流",
	"长鲸帮" : "郑起云",
	"金龙帮" : "焦公礼",
	"渤海帮" : "洪胜海",
	"青竹帮" : "程青竹",
	"鄱阳帮" : "梁银龙",
	"龙游帮" : "荣彩本",
]);

string *empty_bangs = ({
	"巫山帮",
	"三江帮",
	"海沙帮",
	"巨鲸帮",
	"神乌帮",
});

string *bang_places = ({
	"/d/city/jiaowai1",
	"/d/beijing/xichangdamen",
	"/d/chengdu/dongjie2",
	"/d/changan/eastroad2",
	"/d/emei/caodi",
	"/d/foshan/road5",
	"/d/fuzhou/fzroad8",
	"/d/hangzhou/road5",
	"/d/hanzhong/minju2",
	"/d/hengshan/shandao2",
	"/d/henshan/shanlu7",
	"/d/huanghe/wufosi",
	"/d/huashan/path1",
	"/d/jiangling/guiyuansi",
	"/d/jiaxing/road2",
	"/d/kunlun/shanlin4",
	"/d/lanzhou/caoyuan2",
	"/d/lingzhou/xuanhebao",
	"/d/luoyang/lvzhuxiaoyuan",
	"/d/qilian/ailaoshan",
	"/d/qingcheng/sanwanjiudao",
	"/d/quanzhen/shanlu11",
	"/d/quanzhou/caoan",
	"/d/shouxihu/pingtai5",
	"/d/shaolin/shijie7",
	"/d/shenlong/caodi",
	"/d/songshan/songyueta",
	"/d/suzhou/wenmeige",
	"/d/taishan/xitian",
	"/d/tiezhang/pingtai",
	"/d/village/temple1",
	"/d/wanjiegu/shan_road1",
	"/d/wudang/jinding",
	"/d/wuliang/road5",
	"/d/wuxi/eastroad2",
	"/d/xiaoyao/muwu1",
	"/d/xiangyang/caodi6",
	"/d/xingxiu/shanjiao",
	"/d/xuedao/sroad4",
	"/d/yueyang/longsheshan",
});

string *show_regions = ({
	"city",
	"emei",
	"suzhou",
	"foshan",
	"hangzhou",
	"huashan",
	"jiaxing",
	"quanzhou",
	"shaolin",
	"hengshan",
	"taishan",
	"village",
	"wudang",
});
